### ISSUE TITLE
navigateFromEvent not available?

### ISSUE THREAD

**Issue by cmcconomy** [RoundingWellOS/backbone.eventrouter#11]
In the readme, an example is provided: `myEventRouter.navigateFromEvent('some:event', 'foo');`

however, looking at the code ( https://github.com/RoundingWellOS/backbone.eventrouter/blob/master/dist/backbone.eventrouter.js#L98 ) the API appears to be different.

Furthermore, the 'latest' version pulled from bower.io is 0.1.0 and doesn't include the method at all.

**Comment by paulfalgout** [comment]
Wow! Sorry for the very long reply.  This somehow escaped my alerts.

So navigateFromEvent does support that API.. it will take N arguments after the event name.. so `myEventRouter.navigateFromEvent('some:event', 'foo', 'bar', 'baz');` everything just gets pushed along in the `arguments`

I'm surprised at bower.. I'll check into that.  We might need to push a minor version or something, but something seems funny.

**Comment by paulfalgout** [comment]
Alright version bumped and re-published.  This should be resolved.
